# TODO: Delete this action when we migrate off JReleaser for all our releases

name: JReleaser check
description: Smoke tests that checks our jreleaser release command works
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Gradle
      uses: awslabs/aws-kotlin-repo-tools/.github/actions/configure-gradle@main

    - name: Test jreleaserFullRelease
      shell: bash
      run: |
        export JRELEASER_PROJECT_JAVA_GROUP_ID="com.sonatype.central.testing.amazon"
        export JRELEASER_MAVENCENTRAL_STAGE="UPLOAD"
        
        export JRELEASER_MAVENCENTRAL_USERNAME="foobar"
        export JRELEASER_MAVENCENTRAL_TOKEN="foobar"
        
        export JRELEASER_GENERIC_TOKEN="foobar"
        
        export JRELEASER_GPG_PASSPHRASE="foobar"
        export JRELEASER_GPG_PUBLIC_KEY="-----BEGIN PGP PUBLIC KEY BLOCK-----
        -----END PGP PUBLIC KEY BLOCK-----"
        export JRELEASER_GPG_SECRET_KEY="-----BEGIN PGP PRIVATE KEY BLOCK-----
        -----END PGP PRIVATE KEY BLOCK-----"
        
        ./gradlew jreleaserFullRelease --dryrun --stacktrace #TODO: Remove stacktrace
